steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}'
      - '-f'
      - 'services/export-worker/Dockerfile'
      - '.'

images:
  - '${_IMAGE}'