var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/projects/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rid0xq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0.5-~6a.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qy1cql._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.v_h3x._.js")
R.c("server/chunks/ssr/_0h575f0._.js")
R.c("server/chunks/ssr/src_app_opengraph-image--metadata_0ox-fhv.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ksat45._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_0m5ef.s._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_projects_page_actions_08dhj-~.js")
R.m(9607)
module.exports=R.m(9607).exports
