// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/analysis" | "/admin/billing" | "/admin/errors" | "/admin/events" | "/admin/exports" | "/admin/projects" | "/admin/users" | "/api-reference" | "/blog" | "/careers" | "/changelog" | "/dashboard" | "/dashboard/billing" | "/dashboard/diagnostics" | "/dashboard/exports" | "/dashboard/presets" | "/dashboard/processing" | "/dashboard/projects" | "/dashboard/projects/[id]" | "/dashboard/record" | "/dashboard/settings" | "/dashboard/upload" | "/docs" | "/features" | "/login" | "/pricing" | "/privacy" | "/screen-recording-editor" | "/security" | "/templates" | "/terms" | "/tutorials" | "/use-cases"
type AppRouteHandlerRoutes = "/api/admin/analysis" | "/api/admin/billing" | "/api/admin/bootstrap" | "/api/admin/errors" | "/api/admin/events" | "/api/admin/exports" | "/api/admin/overview" | "/api/admin/projects" | "/api/admin/projects/[id]" | "/api/admin/users" | "/api/admin/users/[uid]" | "/api/billing/checkout" | "/api/billing/export-permit" | "/api/billing/health" | "/api/billing/portal" | "/api/billing/webhook" | "/api/chat" | "/api/cron/reconcile-exports" | "/api/export/cancel" | "/api/export/cloud" | "/api/export/download" | "/api/export/retry" | "/api/internal/transcribe" | "/api/projects/[id]/analyze" | "/api/projects/[id]/captions" | "/api/projects/[id]/diagnose" | "/api/projects/[id]/rebalance" | "/api/projects/[id]/reframe" | "/api/projects/[id]/zooms-from-clicks" | "/api/settings/api-keys" | "/api/settings/api-keys/[id]" | "/api/v1/me"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/analysis": {}
  "/admin/billing": {}
  "/admin/errors": {}
  "/admin/events": {}
  "/admin/exports": {}
  "/admin/projects": {}
  "/admin/users": {}
  "/api-reference": {}
  "/api/admin/analysis": {}
  "/api/admin/billing": {}
  "/api/admin/bootstrap": {}
  "/api/admin/errors": {}
  "/api/admin/events": {}
  "/api/admin/exports": {}
  "/api/admin/overview": {}
  "/api/admin/projects": {}
  "/api/admin/projects/[id]": { "id": string; }
  "/api/admin/users": {}
  "/api/admin/users/[uid]": { "uid": string; }
  "/api/billing/checkout": {}
  "/api/billing/export-permit": {}
  "/api/billing/health": {}
  "/api/billing/portal": {}
  "/api/billing/webhook": {}
  "/api/chat": {}
  "/api/cron/reconcile-exports": {}
  "/api/export/cancel": {}
  "/api/export/cloud": {}
  "/api/export/download": {}
  "/api/export/retry": {}
  "/api/internal/transcribe": {}
  "/api/projects/[id]/analyze": { "id": string; }
  "/api/projects/[id]/captions": { "id": string; }
  "/api/projects/[id]/diagnose": { "id": string; }
  "/api/projects/[id]/rebalance": { "id": string; }
  "/api/projects/[id]/reframe": { "id": string; }
  "/api/projects/[id]/zooms-from-clicks": { "id": string; }
  "/api/settings/api-keys": {}
  "/api/settings/api-keys/[id]": { "id": string; }
  "/api/v1/me": {}
  "/blog": {}
  "/careers": {}
  "/changelog": {}
  "/dashboard": {}
  "/dashboard/billing": {}
  "/dashboard/diagnostics": {}
  "/dashboard/exports": {}
  "/dashboard/presets": {}
  "/dashboard/processing": {}
  "/dashboard/projects": {}
  "/dashboard/projects/[id]": { "id": string; }
  "/dashboard/record": {}
  "/dashboard/settings": {}
  "/dashboard/upload": {}
  "/docs": {}
  "/features": {}
  "/login": {}
  "/pricing": {}
  "/privacy": {}
  "/screen-recording-editor": {}
  "/security": {}
  "/templates": {}
  "/terms": {}
  "/tutorials": {}
  "/use-cases": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
