// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analysis">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing">> = Specific
  const handler = {} as typeof import("../../src/app/admin/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/errors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/errors">> = Specific
  const handler = {} as typeof import("../../src/app/admin/errors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/exports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../src/app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api-reference/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-reference">> = Specific
  const handler = {} as typeof import("../../src/app/api-reference/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../src/app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/diagnostics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/diagnostics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/diagnostics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/presets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/presets">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/presets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/processing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projects">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/record/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/record">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/record/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/upload">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../src/app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/screen-recording-editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/screen-recording-editor">> = Specific
  const handler = {} as typeof import("../../src/app/screen-recording-editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../src/app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../src/app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tutorials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tutorials">> = Specific
  const handler = {} as typeof import("../../src/app/tutorials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/use-cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/use-cases">> = Specific
  const handler = {} as typeof import("../../src/app/use-cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/errors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/errors">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/errors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/exports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[uid]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[uid]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[uid]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/export-permit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/export-permit">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/export-permit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/reconcile-exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/reconcile-exports">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/reconcile-exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/cloud/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/cloud">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/cloud/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/transcribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/captions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/captions">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/captions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/diagnose">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/rebalance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/rebalance">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/rebalance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/reframe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/reframe">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/reframe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/zooms-from-clicks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/zooms-from-clicks">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/zooms-from-clicks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/api-keys/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/api-keys/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/api-keys/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
