var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/api-reference/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~.cmej._.js")
R.c("server/chunks/ssr/node_modules_0ewn5.s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0je1glf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qy1cql._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.v_h3x._.js")
R.c("server/chunks/ssr/_0h575f0._.js")
R.c("server/chunks/ssr/src_app_opengraph-image--metadata_0ox-fhv.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ksat45._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_api-reference_page_actions_0bmyoh9.js")
R.m(44153)
module.exports=R.m(44153).exports
