/**
 * THE CURRENT RELEASE — generated by scripts/desktop-release.mjs.
 *
 * Do not edit the checksums or sizes by hand: they describe the exact files the
 * release script hashed, and a number that drifts from the artifact behind it
 * is worse than no checksum at all. Re-run the script instead.
 *
 * `status` is the one field a human changes, and only by re-running with
 * `--publish` once the packaged app has passed end-to-end verification.
 * Publishing turns on the public download AND the website's desktop gate in the
 * same edit — see src/lib/desktop/release.ts for why those are coupled.
 */
import type { DesktopRelease } from "./release";

export const CURRENT_RELEASE: DesktopRelease = {
  "version": "0.1.0",
  "channel": "stable",
  "status": "draft",
  "releasedAt": "2026-07-30",
  "notes": [
    "First public build of the Framevo desktop app.",
    "Local-first editing: projects, media and the timeline live on your machine.",
    "Local GPU-accelerated MP4 export using the same render core as cloud exports.",
    "Sign in with your Framevo account to sync cloud projects; works offline either way.",
    "Automatic updates, installed on quit so an export is never interrupted."
  ],
  "assets": [
    {
      "platform": "windows",
      "arch": "x64",
      "url": "REPLACE_ME/0.1.0/Framevo-Setup.exe",
      "filename": "Framevo-Setup.exe",
      "sizeBytes": 205083648,
      "sha256": "1fe9e69f7c46d58da58cc6adc2271e5efa7cf526c49a6b94f90001900a9b4cca",
      "minimumOs": "Windows 10 (64-bit) or later"
    }
  ]
};
