/**
 * THE CURRENT RELEASE — generated by scripts/desktop-release.mjs.
 *
 * Do not edit the checksums or sizes by hand: they describe the exact files the
 * release script hashed, and a number that drifts from the artifact behind it
 * is worse than no checksum at all. Re-run the script instead.
 *
 * `status` is the one field a human changes, and only by re-running with
 * `--publish` once the packaged app has passed end-to-end verification.
 * Publishing turns on the public download for every platform listed in
 * `assets`. The desktop-first gate additionally waits until EVERY supported
 * platform ships an installer (see `gateReady` in release.ts), so a
 * Windows-only publish serves downloads without blocking web editing anywhere.
 */
import type { DesktopRelease } from "./release";

export const CURRENT_RELEASE: DesktopRelease = {
  "version": "0.1.0",
  "channel": "stable",
  "status": "published",
  "releasedAt": "2026-08-25",
  "notes": [
    "First public build of the Framevo desktop app.",
    "Local-first editing: projects, media and the timeline live on your machine.",
    "Local GPU-accelerated MP4 export using the same render core as cloud exports.",
    "Sign in with your Framevo account to sync cloud projects; works offline either way.",
    "Automatic updates, installed on quit so an export is never interrupted."
  ],
  "assets": [
    {
      "platform": "windows",
      "arch": "x64",
      "url": "https://storage.googleapis.com/adzoom-prod.firebasestorage.app/desktop/releases/0.1.0/Framevo-Setup.exe",
      "filename": "Framevo-Setup.exe",
      "sizeBytes": 205113344,
      "sha256": "6e076dc970628e6662b7e88d6dc782205d97c8328f5dec9fe417e57cd778cd86",
      "minimumOs": "Windows 10 (64-bit) or later"
    }
  ],
  "updateFeedUrl": "https://storage.googleapis.com/adzoom-prod.firebasestorage.app/desktop/releases/stable"
};
